# Config for Yarn. <Last updated: 2025-01-01>

# Compression level employed for zip archives (yarn cache).
# See https://yarnpkg.com/configuration/yarnrc#compressionLevel
compressionLevel: mixed

# Define whether the cache should be shared between all local projects
# See https://yarnpkg.com/configuration/yarnrc#enableGlobalCache
enableGlobalCache: false

# Define how Node packages should be installed.
# See https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules
